############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Local Information"
url = "local-information/"
weight = 2

[[main]]
name = "History"
url = "history/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
weight = 5
name = "More"
hasChildren = true

  [[main]]
  parent = "More"
  name = "FAQ"
  url = "faq/"
  weight = 1

[[main]]
name = "About"
url = "about/"
weight = 6

[[main]]
name = "Contact"
url = "contact/"
weight = 7


# footer menu
[[footer]]
name = "Local Information"
url = "local-information/"
weight = 2

[[footer]]
name = "FAQ"
url = "faq/"
weight = 3

[[footer]]
name = "About"
url = "about/"
weight = 4

[[footer]]
name = "Contact"
url = "contact/"
weight = 5
